### PR TITLE
DNS Implementation + Client improvements + Current config

### PR DESCRIPTION
**Pull request by valentinbreiz**
to do :
- [x] implement multiple queries
- [x] DNS Response
- [x] handle errors
- [x] integrate DNS to ping

### CODE REVIEW

**Comment by valentinbreiz** [comment]
image

**Comment by valentinbreiz** [comment]
image

**Comment by valentinbreiz** [comment]
Blocked by https://github.com/aura-systems/Aura-Operating-System/issues/173

image

**Comment by geomtech** [comment]
Hi Valentin, there is also one feature to make for DNS. It's to know a dns name from the IP.

Like this :

`dns 1.1.1.1`

Will give :

`one.one.one.one`

**Comment by valentinbreiz** [comment]
I don't understand, you're talking about that?
image

**Comment by geomtech** [comment]
image

**Review by geomtech — APPROVED** [review]

**Pull request merged**
